import { NextPage } from "next";
import Head from 'next/head'
import Banner from "../components/common/banner/banner";
import Layout from "../components/common/layout";
import styles from "../styles/contact.module.scss"
import { request } from "../libs/datocms";
import { useEffect, useState } from "react";

const INFOS_QUERY = `query HomePage($limit: IntType) {
  allInfos(first: $limit) {
    id
    title
    text
  }
}`;

export async function getStaticProps() {
  const data = await request({
    query: INFOS_QUERY,
    variables: { limit: 10 },
    preview: null
  });
  return {
    props: data
  };
}

export interface InfoItem {
  id: string,
  title: string,
  text: string
}

const Contact: NextPage = () => {
  const [infoData, setInfoData] = useState<InfoItem[] | []>([])

  useEffect(() => {
    request({
      query: INFOS_QUERY,
      variables: { limit: 10 },
      preview: null
    }).then(res => {
      setInfoData(res.allInfos)
    })
  }, [])


  let infoList = null;

  if (infoData?.length) {
    infoList = infoData.map(info => 
    <li key={info.id}><span className={styles.infoTitle}>{info.title}</span> : {info.text}</li>
    )
  }
    
    return (
      <Layout> 
        <Head>
          <title>PMS électronique - Contact</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Banner text="Contact et prise en charge du matériel"/>
        <section className={styles.section}>
          <article>
            <h2>Infos</h2>
            {infoList ? 
              <div className={styles.infosSection}>
                  <ul>
                    {infoList}
                  </ul>
              </div>
            : null}
            <div className={styles.infosSection}>
              <h4>Contact</h4>
              <p><strong>E-mail</strong> : pms.elec@free.fr <br />
              <strong>Tel</strong> : 06 35 96 86 31</p>
            </div>
            <div className={styles.infosSection}>
              <h4>{"Horaires de l'atelier"}</h4>
              <p>
                <strong>Lundi - jeudi</strong> : 10h à 12h et 13h30 à 18h <br />
                <strong>Vendredi</strong> : 10h à 12h et 13h30 à 17h30
              </p>
            </div>
            <div className={styles.infosSection}>
              <h4>{"L'atelier recommande"}</h4>
              <p>
                <a href="https://www.alh-effects.fr" target="_blank" rel="noreferrer" ><u><strong>ALH effects</strong></u> - De magnifiques pédales boutiques</a> <br/>
                <a href="https://www.facebook.com/Marty.Pedalboard/" target="_blank" rel="noreferrer" ><u><strong>Marty pedalboards</strong></u> - Des pedalboards sur mesure</a>
              </p>
            </div>
          
          </article>
          <div className={styles.separator}></div>
          <article>
            <h2>Prise en charge du matériel</h2>
            <div className={styles.infosSection}> 
              <h3>Chez Hurricane musique - Vertou</h3>
              <p>PMS électronique travaille en collaboration avec <strong>HURRICANE MUSIQUE</strong>. Vous pouvez y déposer votre matériel aux horaires {"d'ouverture"} du magasin, <u><strong>après {"m'avoir"} téléphoné et reçu un numéro de prise en charge</strong></u>.</p>
              <p>
                <strong>Adresse du magasin:</strong> 16 allée des cinq continents ZAC Pôle Sud - 44120 Vertou
              </p>
              <p><u><a href="https://hurricanemusic.fr" target="_blank" rel="noreferrer" >Accéder au site {"d'Hurricane"} musique</a></u></p>
              <p>{"Ne montez plus votre materiel à l'étage, il sera stocké au RDC après que vous vous soyez présenté"}</p>
            </div>
          
            <div>
              <h3>{"A l'atelier"}</h3>
              <p>{"Possibilité de déposer votre matériel à l'atelier"}, <u><strong>sur rendez-vous téléphonique uniquement</strong></u></p>
            </div>
            
          </article>
          <div className={styles.separator}></div>
          <p className={styles.siret}>
            P.M.S électronique est une société inscrite au répertoire des métiers (SIRET:42139360400036)
            </p>
        </section>
      </Layout>

    )
}

export default Contact;
