import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/index.module.scss'
import Layout from '../components/common/layout'
import Divider from '../components/common/divider'
import Banner from '../components/common/banner/banner'
import serviceImg from '../public/images/lampemetre.jpg'
import expertiseImg from '../public/images/orange.jpg'
import commimentsImg from '../public/images/insideAmp.jpg'

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>PMS électronique - {"L'atelier"}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner text="PMS électronique" subText="Spécialiste de l'amplification à lampes"/>
      <section className={styles.hero}>
        <h2>{"P.M.S électronique est un atelier spécialisé dans la réparation des amplificateurs instruments et autre matériel audio"} </h2>
        <p>{"Localisé en région Nantaise, PMS électronique s'adresse aussi bien aux particuliers qu'aux professionnels soucieux d'un service réactif et de qualité"}</p>
      </section>

      <Divider />

      <section>
        <article className={[styles.imageOnRight, styles.homeArticle].join(' ')}>
          <div className={styles.textContainer}>
            <h2>Services</h2>
            <p className={styles.subTitle}>Sur amplis à lampes ou transistors (instruments et hifi), effets, claviers, matériel vintage et de sonorisation :</p>
            <ul>
              <li>- Révisions</li>
              <li>- Réparations</li>
              <li>- Modifications</li>
              <li>- Conseils</li>
              <li>- Optimisation</li>
            </ul>
          </div>
            
          <div className={styles.imageContainer}>
            <Image 
              src={serviceImg}
              alt="lampemetre"
              layout="responsive"
            />
          </div>
        </article>
        <article className={[styles.imageOnLeft, styles.homeArticle].join(' ')}>
          <div className={styles.textContainer}>
            <h2>Compétences</h2>
            <p>Connaissances approfondies sur : Marshall, Fender, Hiwatt, Vox, Orange, Laney, H.K, Mesa-boogie, Boss, Roland, E.H, Peavey, T-REX...</p>
            <p>Optimisation des amplis à chaque retubage en sélectionnant les tubes en fonction de votre style de musique !</p>
            <p>Appairage des tubes au lampe-mètre.</p>
          </div>
          <div className={styles.imageContainer}>
            <Image 
              src={expertiseImg}
              alt="orange amp"
              layout="responsive"
              height="300px"
              className="image"
            />
          </div>
          <p>{"L'atelier est équipé en : oscilloscopes, générateur de fréquence, multimètre, lampe-mètre, testeur de composants actifs, charges fictives, ..."}</p>
        </article>
        <article className={[styles.imageOnRight, styles.homeArticle].join(' ')}>
          <div className={styles.textContainer}>
            <h2>Nos engagements</h2>
            <p className={styles.subTitle}>{"L'atelier s'engage à :"}</p>
            <ul>
              <li>- Vous proposer des <strong>devis gratuits</strong>  !</li>
              <li>- Vous informer sur le suivi des interventions (mail ou tel)</li>
              <li>- Travailler en toute clarté (respect des tarifs, retour des pièces défectueuses, ...)</li>
              <li>- Vous proposer un service de qualité et <strong>sous garantie pendant 3 mois</strong></li>
              <li>- Rester disponible et à votre écoute (même hors garantie)</li>
              <li>- Garantir des délais respectables (urgence prise en compte)</li>
              <li>- Vous proposer un <strong>tarif horaire compétitif et adapté</strong> {"(48€/h ttc et fractionnable en quarts d'heure)"}</li>
              <li>- Vous conseiller au mieux et dans votre intérêt.</li>
              <li>- Optimiser vos amplis à tubes en tenant compte de votre style musical.</li>
              <li>- Si besoin installer les tubes, ou composants, que vous fournirez.</li>
              <li>- Et surtout, <strong>fiabiliser et faire sonner au mieux vos amplis !</strong></li>
            </ul>
          </div>
          <div className={styles.imageContainer}>
          <Image 
              src={commimentsImg}
              alt="lampemetre"
              layout="responsive"
            />
          </div>
        </article>
      </section>
    </Layout>
  )
}

export default Home
